### ISSUE TITLE
Multiprocessing error when aligning

### ISSUE THREAD

**Issue by Johndirr** [benfmiller/audalign#16]
Sorry to bother you again.
I used audalign to convert two video files to wav. This worked like a charm. Now I was trying to align the output: 

```
import audalign

ada = audalign.Audalign()

...

ada.convert_audio_file(filepath1, filepath1wav)
ada.convert_audio_file(filepath2, filepath2wav)

print(ada.align(r'.\files'))
```

I get the following error then:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\retrohelix\appdata\local\programs\python\python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "c:\users\retrohelix\appdata\local\programs\python\python38\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "c:\users\retrohelix\appdata\local\programs\python\python38\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "c:\users\retrohelix\appdata\local\programs\python\python38\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "c:\users\retrohelix\appdata\local\programs\python\python38\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "c:\users\retrohelix\appdata\local\programs\python\python38\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\users\retrohelix\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\RetroHelix\Programming\Audio\aligndashit.py", line 12, in <module>
    print(ada.align(r'.\files'))
  File "C:\Users\RetroHelix\Envs\audalignPy38\lib\site-packages\audalign\__init__.py", line 528, in align
    self.fingerprint_directory(directory_path)
  File "C:\Users\RetroHelix\Envs\audalignPy38\lib\site-packages\audalign\__init__.py", line 223, in fingerprint_directory
    result = self._fingerprint_directory(path, plot, nprocesses, extensions)
  File "C:\Users\RetroHelix\Envs\audalignPy38\lib\site-packages\audalign\__init__.py", line 289, in _fingerprint_directory
    with multiprocessing.Pool(nprocesses) as self.pool:
  File "c:\users\retrohelix\appdata\local\programs\python\python38\lib\multiprocessing\context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "c:\users\retrohelix\appdata\local\programs\python\python38\lib\multiprocessing\pool.py", line 212, in __init__
    self._repopulate_pool()
  File "c:\users\retrohelix\appdata\local\programs\python\python38\lib\multiprocessing\pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "c:\users\retrohelix\appdata\local\programs\python\python38\lib\multiprocessing\pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "c:\users\retrohelix\appdata\local\programs\python\python38\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "c:\users\retrohelix\appdata\local\programs\python\python38\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "c:\users\retrohelix\appdata\local\programs\python\python38\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "c:\users\retrohelix\appdata\local\programs\python\python38\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "c:\users\retrohelix\appdata\local\programs\python\python38\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

```

**Comment by benfmiller** [comment]
This is actually a fun error that multiprocessing on windows throws if you don't wrap it in an if __name__ == "__main__": block.
Windows handles multiprocessing differently than Unix systems.
This error doesn't ever occur in a python repl session, either, I'm pretty sure.

I usually toss everything in a main() function and call 
```[p]
if __name__ == "__main__":
    main()
```
and it runs.

**Comment by Johndirr** [comment]
Nice, so I can fix it myself. Thanks for the info and sorry for the wrong issue.
